// packages/svelte/src/components/DotBounce/DotBounce.svelte
<script lang="ts">
  import type { DotBounceProps } from '@jolt/core';
  import '@jolt/core/styles/dot-bounce.css';

  let { color = '#6d5efc', size = 12, speed = 1.2, label = 'Loading…' }: DotBounceProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-dot-bounce"
  style="--jolt-color:{color};--jolt-size:{size}px;--jolt-speed:{speed}s"
>
  <span></span>
  <span></span>
  <span></span>
</div>

// packages/vue/src/components/DotBounce/DotBounce.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/dot-bounce.css';

// Mirrors `dotBounceSchema` in @jolt/core (see DECISIONS D-011).
interface Props {
  color?: string;
  size?: number;
  speed?: number;
  label?: string;
}
const { color = '#6d5efc', size = 12, speed = 1.2, label = 'Loading…' } = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-size': `${size}px`,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <div role="status" :aria-label="label" class="jolt-dot-bounce" :style="style">
    <span />
    <span />
    <span />
  </div>
</template>
