// packages/react/src/components/Aurora/Aurora.tsx
import { useLayoutEffect, useRef } from 'react';
import type { AuroraProps } from '@jolt/core';
import { createAurora } from '@jolt/core/webgl/aurora';

/** A decorative flowing aurora light-curtain (Three.js custom shader), full-bleed canvas. */
export function Aurora({ colors, speed, intensity, scale, opacity }: AuroraProps) {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = createAurora(el, { colors, speed, intensity, scale, opacity });
    return () => controller.revert();
  }, [colors, speed, intensity, scale, opacity]);

  return <div ref={ref} aria-hidden="true" className="h-full w-full" />;
}

// packages/svelte/src/components/Aurora/Aurora.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { AuroraProps } from '@jolt/core';
  import { createAurora } from '@jolt/core/webgl/aurora';

  let { colors, speed, intensity, scale, opacity }: AuroraProps = $props();
  let root: HTMLDivElement;

  onMount(() => {
    const controller = createAurora(root, { colors, speed, intensity, scale, opacity });
    return () => controller.revert();
  });
</script>

<div bind:this={root} aria-hidden="true" class="h-full w-full"></div>
