// packages/react/src/components/DotBounce/DotBounce.tsx
import type { CSSProperties } from 'react';
import type { DotBounceProps } from '@jolt/core';
import '@jolt/core/styles/dot-bounce.css';

/** Three bouncing dots (CSS-only loader). Exposes role="status" with an accessible label. */
export function DotBounce({
  color = '#6d5efc',
  size = 12,
  speed = 1.2,
  label = 'Loading…',
}: DotBounceProps) {
  const style = {
    '--jolt-color': color,
    '--jolt-size': `${size}px`,
    '--jolt-speed': `${speed}s`,
  } as CSSProperties;

  return (
    <div role="status" aria-label={label} className="jolt-dot-bounce" style={style}>
      <span />
      <span />
      <span />
    </div>
  );
}

// packages/svelte/src/components/DotBounce/DotBounce.svelte
<script lang="ts">
  import type { DotBounceProps } from '@jolt/core';
  import '@jolt/core/styles/dot-bounce.css';

  let { color = '#6d5efc', size = 12, speed = 1.2, label = 'Loading…' }: DotBounceProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-dot-bounce"
  style="--jolt-color:{color};--jolt-size:{size}px;--jolt-speed:{speed}s"
>
  <span></span>
  <span></span>
  <span></span>
</div>
