// packages/svelte/src/components/Sweep/Sweep.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { SweepProps } from '@jolt/core';
  import '@jolt/core/styles/sweep.css';

  type Props = SweepProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#7c5cff',
    speed = 0.3,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {...rest}
  {type}
  class="jolt-sweep {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>

// packages/react/src/components/Sweep/Sweep.tsx
import type { ButtonHTMLAttributes, CSSProperties } from 'react';
import type { SweepProps as SweepStyleProps } from '@jolt/core';
import '@jolt/core/styles/sweep.css';

type SweepProps = SweepStyleProps & ButtonHTMLAttributes<HTMLButtonElement>;

/** A ghost button whose fill wipes in on hover (CSS-only). Renders a real <button>. */
export function Sweep({
  color = '#7c5cff',
  speed = 0.3,
  label = 'Button',
  type = 'button',
  className,
  style,
  children,
  ...rest
}: SweepProps) {
  const vars = {
    '--jolt-color': color,
    '--jolt-speed': `${speed}s`,
    ...style,
  } as CSSProperties;

  return (
    <button
      {...rest}
      type={type}
      className={`jolt-sweep${className ? ` ${className}` : ''}`}
      style={vars}
    >
      {children ?? label}
    </button>
  );
}
