// packages/vue/src/components/ScrollVelocity/ScrollVelocity.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue';
import { createScrollVelocity, type ScrollVelocityController } from '@jolt/core';

// Mirrors `scrollVelocitySchema` in @jolt/core (Vue's SFC compiler can't resolve the
// schema-inferred type in defineProps — see DECISIONS D-011).
interface Props {
  text: string;
  baseVelocity?: number;
  direction?: 'left' | 'right';
}
const props = defineProps<Props>();
const root = ref<HTMLSpanElement | null>(null);
const copies = 8;
let controller: ScrollVelocityController | null = null;

onMounted(() => {
  if (root.value) controller = createScrollVelocity(root.value, props);
});
onBeforeUnmount(() => controller?.revert());
</script>

<template>
  <span ref="root" class="block overflow-hidden whitespace-nowrap" :aria-label="props.text"
    ><span class="inline-block will-change-transform" data-jolt-track aria-hidden="true"
      ><span v-for="i in copies" :key="i" class="inline-block pr-8">{{ props.text }}</span></span
    ></span
  >
</template>

// packages/svelte/src/components/ScrollVelocity/ScrollVelocity.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createScrollVelocity, type ScrollVelocityProps } from '@jolt/core';

  let { text, baseVelocity, direction }: ScrollVelocityProps = $props();
  let root: HTMLSpanElement;
  const copies = [...Array(8).keys()];

  onMount(() => {
    const controller = createScrollVelocity(root, { text, baseVelocity, direction });
    return () => controller.revert();
  });
</script>

<!-- prettier-ignore -->
<span bind:this={root} class="block overflow-hidden whitespace-nowrap" aria-label={text}><span class="inline-block will-change-transform" data-jolt-track aria-hidden="true">{#each copies as i (i)}<span class="inline-block pr-8">{text}</span>{/each}</span></span>
