// packages/svelte/src/components/Spinner/Spinner.svelte
<script lang="ts">
  import type { SpinnerProps } from '@jolt/core';
  import '@jolt/core/styles/spinner.css';

  let {
    color = '#7c5cff',
    size = 40,
    thickness = 4,
    speed = 0.8,
    label = 'Loading…',
  }: SpinnerProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-spinner"
  style="--jolt-color:{color};--jolt-size:{size}px;--jolt-thickness:{thickness}px;--jolt-speed:{speed}s"
></div>

// packages/react/src/components/Spinner/Spinner.tsx
import type { CSSProperties } from 'react';
import type { SpinnerProps } from '@jolt/core';
import '@jolt/core/styles/spinner.css';

/** A rotating-ring loading spinner (CSS-only). Exposes role="status" with an accessible label. */
export function Spinner({
  color = '#7c5cff',
  size = 40,
  thickness = 4,
  speed = 0.8,
  label = 'Loading…',
}: SpinnerProps) {
  const style = {
    '--jolt-color': color,
    '--jolt-size': `${size}px`,
    '--jolt-thickness': `${thickness}px`,
    '--jolt-speed': `${speed}s`,
  } as CSSProperties;

  return <div role="status" aria-label={label} className="jolt-spinner" style={style} />;
}
