// packages/svelte/src/components/ScrollVelocity/ScrollVelocity.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createScrollVelocity, type ScrollVelocityProps } from '@jolt/core';

  let { text, baseVelocity, direction }: ScrollVelocityProps = $props();
  let root: HTMLSpanElement;
  const copies = [...Array(8).keys()];

  onMount(() => {
    const controller = createScrollVelocity(root, { text, baseVelocity, direction });
    return () => controller.revert();
  });
</script>

<!-- prettier-ignore -->
<span bind:this={root} class="block overflow-hidden whitespace-nowrap" aria-label={text}><span class="inline-block will-change-transform" data-jolt-track aria-hidden="true">{#each copies as i (i)}<span class="inline-block pr-8">{text}</span>{/each}</span></span>

// packages/react/src/components/ScrollVelocity/ScrollVelocity.tsx
import { useLayoutEffect, useRef } from 'react';
import { createScrollVelocity, type ScrollVelocityProps } from '@jolt/core';

/** Copies of the text rendered into the track so the marquee can loop seamlessly. */
const COPIES = 8;

/** A horizontal marquee whose speed + direction react to scroll velocity (GSAP). */
export function ScrollVelocity({ text, baseVelocity, direction }: ScrollVelocityProps) {
  const ref = useRef<HTMLSpanElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = createScrollVelocity(el, { text, baseVelocity, direction });
    return () => controller.revert();
  }, [text, baseVelocity, direction]);

  return (
    <span ref={ref} className="block overflow-hidden whitespace-nowrap" aria-label={text}>
      <span className="inline-block will-change-transform" data-jolt-track aria-hidden="true">
        {[...Array(COPIES).keys()].map((i) => (
          <span key={i} className="inline-block pr-8">
            {text}
          </span>
        ))}
      </span>
    </span>
  );
}
