// packages/svelte/src/components/Scramble/Scramble.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { createScramble, type ScrambleProps } from '@jolt/core';

  let { text, duration, delay, chars, revealDelay, speed }: ScrambleProps = $props();
  let root: HTMLSpanElement;

  onMount(() => {
    const controller = createScramble(root, { text, duration, delay, chars, revealDelay, speed });
    return () => controller.revert();
  });
</script>

<span bind:this={root} aria-label={text}>{text}</span>

// packages/react/src/components/Scramble/Scramble.tsx
import { useLayoutEffect, useRef } from 'react';
import { createScramble, type ScrambleProps } from '@jolt/core';

/** Text that decodes into place from a churn of random characters on mount (GSAP). */
export function Scramble({ text, duration, delay, chars, revealDelay, speed }: ScrambleProps) {
  const ref = useRef<HTMLSpanElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = createScramble(el, { text, duration, delay, chars, revealDelay, speed });
    return () => controller.revert();
  }, [text, duration, delay, chars, revealDelay, speed]);

  return (
    <span ref={ref} aria-label={text}>
      {text}
    </span>
  );
}
