// packages/svelte/src/components/Sweep/Sweep.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { SweepProps } from '@jolt/core';
  import '@jolt/core/styles/sweep.css';

  type Props = SweepProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#7c5cff',
    speed = 0.3,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {...rest}
  {type}
  class="jolt-sweep {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>

// packages/vue/src/components/Sweep/Sweep.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/sweep.css';

// Mirrors `sweepSchema` in @jolt/core (D-011). Native button attrs fall through to the
// single root <button>; no defineEmits.
interface Props {
  color?: string;
  speed?: number;
  label?: string;
}
const { color = '#7c5cff', speed = 0.3, label = 'Button' } = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <button class="jolt-sweep" :style="style">
    <slot>{{ label }}</slot>
  </button>
</template>
