// packages/react/src/components/Particles/Particles.tsx
import { useLayoutEffect, useRef } from 'react';
import type { ParticlesProps } from '@jolt/core';
import { createParticles } from '@jolt/core/webgl/particles';

/** A decorative drifting WebGL point field (Three.js), rendered to a full-bleed canvas. */
export function Particles({ count, color, size, speed, spread, opacity }: ParticlesProps) {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = createParticles(el, { count, color, size, speed, spread, opacity });
    return () => controller.revert();
  }, [count, color, size, speed, spread, opacity]);

  return <div ref={ref} aria-hidden="true" className="h-full w-full" />;
}

// packages/svelte/src/components/Particles/Particles.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { ParticlesProps } from '@jolt/core';
  import { createParticles } from '@jolt/core/webgl/particles';

  let { count, color, size, speed, spread, opacity }: ParticlesProps = $props();
  let root: HTMLDivElement;

  onMount(() => {
    const controller = createParticles(root, { count, color, size, speed, spread, opacity });
    return () => controller.revert();
  });
</script>

<div bind:this={root} aria-hidden="true" class="h-full w-full"></div>
