// packages/react/src/components/Bars/Bars.tsx
import type { CSSProperties } from 'react';
import type { BarsProps } from '@jolt/core';
import '@jolt/core/styles/bars.css';

/** Five equalizer bars (CSS-only loader). Exposes role="status" with an accessible label. */
export function Bars({ color = '#6d5efc', size = 32, speed = 1, label = 'Loading…' }: BarsProps) {
  const style = {
    '--jolt-color': color,
    '--jolt-size': `${size}px`,
    '--jolt-speed': `${speed}s`,
  } as CSSProperties;

  return (
    <div role="status" aria-label={label} className="jolt-bars" style={style}>
      <span />
      <span />
      <span />
      <span />
      <span />
    </div>
  );
}

// packages/svelte/src/components/Bars/Bars.svelte
<script lang="ts">
  import type { BarsProps } from '@jolt/core';
  import '@jolt/core/styles/bars.css';

  let { color = '#6d5efc', size = 32, speed = 1, label = 'Loading…' }: BarsProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-bars"
  style="--jolt-color:{color};--jolt-size:{size}px;--jolt-speed:{speed}s"
>
  <span></span>
  <span></span>
  <span></span>
  <span></span>
  <span></span>
</div>
