// packages/vue/src/components/Bars/Bars.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/bars.css';

// Mirrors `barsSchema` in @jolt/core (see DECISIONS D-011).
interface Props {
  color?: string;
  size?: number;
  speed?: number;
  label?: string;
}
const { color = '#6d5efc', size = 32, speed = 1, label = 'Loading…' } = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-size': `${size}px`,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <div role="status" :aria-label="label" class="jolt-bars" :style="style">
    <span />
    <span />
    <span />
    <span />
    <span />
  </div>
</template>

// packages/svelte/src/components/Bars/Bars.svelte
<script lang="ts">
  import type { BarsProps } from '@jolt/core';
  import '@jolt/core/styles/bars.css';

  let { color = '#6d5efc', size = 32, speed = 1, label = 'Loading…' }: BarsProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-bars"
  style="--jolt-color:{color};--jolt-size:{size}px;--jolt-speed:{speed}s"
>
  <span></span>
  <span></span>
  <span></span>
  <span></span>
  <span></span>
</div>
