// packages/svelte/src/components/Wave/Wave.svelte
<script lang="ts">
  import { splitSegments, type WaveProps } from '@jolt/core';
  import '@jolt/core/styles/wave.css';

  let {
    text,
    by = 'chars',
    amplitude = 10,
    duration = 1.5,
    stagger = 0.08,
    delay = 0,
  }: WaveProps = $props();
  const segments = $derived(splitSegments(text, by));
</script>

<!-- prettier-ignore -->
<span class="jolt-wave" aria-label={text} style="--jolt-amplitude:{amplitude}px; --jolt-duration:{duration}s; --jolt-stagger:{stagger}s; --jolt-delay:{delay}s">{#each segments as segment, i (i)}<span data-jolt-segment aria-hidden="true" style="--jolt-i:{i}">{segment}</span>{/each}</span>

// packages/react/src/components/Wave/Wave.tsx
import type { CSSProperties } from 'react';
import { splitSegments, type WaveProps } from '@jolt/core';
import '@jolt/core/styles/wave.css';

/** CSS-only per-character vertical wave. */
export function Wave({
  text,
  by = 'chars',
  amplitude = 10,
  duration = 1.5,
  stagger = 0.08,
  delay = 0,
}: WaveProps) {
  const segments = splitSegments(text, by);
  const rootStyle = {
    '--jolt-amplitude': `${amplitude}px`,
    '--jolt-duration': `${duration}s`,
    '--jolt-stagger': `${stagger}s`,
    '--jolt-delay': `${delay}s`,
  } as CSSProperties;

  return (
    <span className="jolt-wave" aria-label={text} style={rootStyle}>
      {segments.map((segment, i) => (
        <span
          key={i}
          data-jolt-segment=""
          aria-hidden="true"
          style={{ '--jolt-i': i } as CSSProperties}
        >
          {segment}
        </span>
      ))}
    </span>
  );
}
