// packages/svelte/src/components/Gradient/Gradient.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { GradientProps } from '@jolt/core';
  import '@jolt/core/styles/gradient.css';

  type Props = GradientProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    colors = ['#7c5cff', '#a855f7', '#ec4899'],
    speed = 4,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();

  // Repeat the first stop so the 200% background scroll loops seamlessly.
  const gradient = $derived(
    `linear-gradient(90deg, ${colors.concat(colors.slice(0, 1)).join(', ')})`,
  );
</script>

<button
  {...rest}
  {type}
  class="jolt-gradient {className}"
  style="--jolt-gradient:{gradient};--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>

// packages/vue/src/components/Gradient/Gradient.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/gradient.css';

// Mirrors `gradientSchema` in @jolt/core (D-011). Native button attrs fall through to
// the single root <button>; no defineEmits.
interface Props {
  colors?: string[];
  speed?: number;
  label?: string;
}
const {
  colors = ['#7c5cff', '#a855f7', '#ec4899'],
  speed = 4,
  label = 'Button',
} = defineProps<Props>();

// Repeat the first stop so the 200% background scroll loops seamlessly.
const style = computed(() => ({
  '--jolt-gradient': `linear-gradient(90deg, ${colors.concat(colors.slice(0, 1)).join(', ')})`,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <button class="jolt-gradient" :style="style">
    <slot>{{ label }}</slot>
  </button>
</template>
