// packages/react/src/components/Tactile/Tactile.tsx
import type { ButtonHTMLAttributes, CSSProperties } from 'react';
import type { TactileProps as TactileStyleProps } from '@jolt/core';
import '@jolt/core/styles/tactile.css';

type TactileProps = TactileStyleProps & ButtonHTMLAttributes<HTMLButtonElement>;

/** A raised button that presses down on click (CSS-only). Renders a real <button>. */
export function Tactile({
  color = '#7c5cff',
  speed = 0.12,
  label = 'Button',
  type = 'button',
  className,
  style,
  children,
  ...rest
}: TactileProps) {
  const vars = {
    '--jolt-color': color,
    '--jolt-speed': `${speed}s`,
    ...style,
  } as CSSProperties;

  return (
    <button
      {...rest}
      type={type}
      className={`jolt-tactile${className ? ` ${className}` : ''}`}
      style={vars}
    >
      {children ?? label}
    </button>
  );
}

// packages/svelte/src/components/Tactile/Tactile.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { TactileProps } from '@jolt/core';
  import '@jolt/core/styles/tactile.css';

  type Props = TactileProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#7c5cff',
    speed = 0.12,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {...rest}
  {type}
  class="jolt-tactile {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>
