// packages/svelte/src/components/Dots/Dots.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { DotsProps } from '@jolt/core';
  import { createDots } from '@jolt/core/webgl/dots';

  let { color, count, size, amplitude, frequency, speed, opacity }: DotsProps = $props();
  let root: HTMLDivElement;

  onMount(() => {
    const controller = createDots(root, {
      color,
      count,
      size,
      amplitude,
      frequency,
      speed,
      opacity,
    });
    return () => controller.revert();
  });
</script>

<div bind:this={root} aria-hidden="true" class="h-full w-full"></div>

// packages/react/src/components/Dots/Dots.tsx
import { useLayoutEffect, useRef } from 'react';
import type { DotsProps } from '@jolt/core';
import { createDots } from '@jolt/core/webgl/dots';

/** A decorative grid of points rippling from the center (Three.js), full-bleed canvas. */
export function Dots({ color, count, size, amplitude, frequency, speed, opacity }: DotsProps) {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = createDots(el, { color, count, size, amplitude, frequency, speed, opacity });
    return () => controller.revert();
  }, [color, count, size, amplitude, frequency, speed, opacity]);

  return <div ref={ref} aria-hidden="true" className="h-full w-full" />;
}
