// packages/svelte/src/components/Tilt/Tilt.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { trackPointer, makeTiltWriter, type TiltProps } from '@jolt/core';
  import '@jolt/core/styles/tilt.css';

  type Props = TiltProps &
    Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#6d5efc',
    maxTilt = 12,
    speed = 0.15,
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();

  let root: HTMLDivElement;
  onMount(() => trackPointer(root, makeTiltWriter(maxTilt)).revert);
</script>

<div
  {...rest}
  bind:this={root}
  class="jolt-tilt {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
>
  {#if children}{@render children()}{/if}
</div>

// packages/react/src/components/Tilt/Tilt.tsx
import { useLayoutEffect, useRef, type HTMLAttributes, type CSSProperties } from 'react';
import { trackPointer, makeTiltWriter, type TiltProps as TiltStyleProps } from '@jolt/core';
import '@jolt/core/styles/tilt.css';

type TiltProps = TiltStyleProps & HTMLAttributes<HTMLDivElement>;

/** A card that rotates in 3-D toward the cursor. Renders a <div> wrapping your content. */
export function Tilt({
  color = '#6d5efc',
  maxTilt = 12,
  speed = 0.15,
  className,
  style,
  children,
  ...rest
}: TiltProps) {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = trackPointer(el, makeTiltWriter(maxTilt));
    return () => controller.revert();
  }, [maxTilt]);

  const vars = {
    '--jolt-color': color,
    '--jolt-speed': `${speed}s`,
    ...style,
  } as CSSProperties;

  return (
    <div
      {...rest}
      ref={ref}
      className={`jolt-tilt${className ? ` ${className}` : ''}`}
      style={vars}
    >
      {children}
    </div>
  );
}
