// packages/vue/src/components/Tilt/Tilt.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, computed } from 'vue';
import { trackPointer, makeTiltWriter, type PointerController } from '@jolt/core';
import '@jolt/core/styles/tilt.css';

// Mirrors `tiltSchema` in @jolt/core (D-011). Native attrs fall through to the single root
// <div>; the 3-D tilt is driven by the shared pointer behavior.
interface Props {
  color?: string;
  maxTilt?: number;
  speed?: number;
}
const { color = '#7c5cff', maxTilt = 12, speed = 0.15 } = defineProps<Props>();

const root = ref<HTMLDivElement | null>(null);
let controller: PointerController | null = null;
onMounted(() => {
  if (root.value) controller = trackPointer(root.value, makeTiltWriter(maxTilt));
});
onBeforeUnmount(() => controller?.revert());

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <div ref="root" class="jolt-tilt" :style="style"><slot /></div>
</template>

// packages/svelte/src/components/Tilt/Tilt.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { trackPointer, makeTiltWriter, type TiltProps } from '@jolt/core';
  import '@jolt/core/styles/tilt.css';

  type Props = TiltProps &
    Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#7c5cff',
    maxTilt = 12,
    speed = 0.15,
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();

  let root: HTMLDivElement;
  onMount(() => trackPointer(root, makeTiltWriter(maxTilt)).revert);
</script>

<div
  {...rest}
  bind:this={root}
  class="jolt-tilt {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
>
  {#if children}{@render children()}{/if}
</div>
