// packages/react/src/components/ShineBorder/ShineBorder.tsx
import type { HTMLAttributes, CSSProperties } from 'react';
import type { ShineBorderProps as ShineBorderStyleProps } from '@jolt/core';
import '@jolt/core/styles/shine-border.css';

type ShineBorderProps = ShineBorderStyleProps & HTMLAttributes<HTMLDivElement>;

/** A card with a gradient border that continuously flows around the perimeter (CSS-only). */
export function ShineBorder({
  color = '#7c5cff',
  speed = 3,
  width = 2,
  className,
  style,
  children,
  ...rest
}: ShineBorderProps) {
  const vars = {
    '--jolt-color': color,
    '--jolt-speed': `${speed}s`,
    '--jolt-width': `${width}px`,
    ...style,
  } as CSSProperties;

  return (
    <div {...rest} className={`jolt-shine-border${className ? ` ${className}` : ''}`} style={vars}>
      {children}
    </div>
  );
}

// packages/svelte/src/components/ShineBorder/ShineBorder.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import type { ShineBorderProps } from '@jolt/core';
  import '@jolt/core/styles/shine-border.css';

  type Props = ShineBorderProps &
    Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#7c5cff',
    speed = 3,
    width = 2,
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<div
  {...rest}
  class="jolt-shine-border {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;--jolt-width:{width}px;{style}"
>
  {#if children}{@render children()}{/if}
</div>
