// packages/vue/src/components/Silk/Silk.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue';
import { createSilk, type SilkController } from '@jolt/core/webgl/silk';

// Mirrors `silkSchema` in @jolt/core (Vue's SFC compiler can't resolve the
// schema-inferred type in defineProps — see DECISIONS D-011).
interface Props {
  colors?: string[];
  speed?: number;
  scale?: number;
  rotation?: number;
  noise?: number;
  opacity?: number;
}
const props = defineProps<Props>();
const root = ref<HTMLDivElement | null>(null);
let controller: SilkController | null = null;

onMounted(() => {
  if (root.value) controller = createSilk(root.value, props);
});
onBeforeUnmount(() => controller?.revert());
</script>

<template>
  <div ref="root" aria-hidden="true" class="h-full w-full" />
</template>

// packages/svelte/src/components/Silk/Silk.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { SilkProps } from '@jolt/core';
  import { createSilk } from '@jolt/core/webgl/silk';

  let { colors, speed, scale, rotation, noise, opacity }: SilkProps = $props();
  let root: HTMLDivElement;

  onMount(() => {
    const controller = createSilk(root, { colors, speed, scale, rotation, noise, opacity });
    return () => controller.revert();
  });
</script>

<div bind:this={root} aria-hidden="true" class="h-full w-full"></div>
