// packages/react/src/components/BorderGlow/BorderGlow.tsx
import { useLayoutEffect, useRef, type HTMLAttributes, type CSSProperties } from 'react';
import {
  trackPointer,
  writeSpotlight,
  type BorderGlowProps as BorderGlowStyleProps,
} from '@jolt/core';
import '@jolt/core/styles/border-glow.css';

type BorderGlowProps = BorderGlowStyleProps & HTMLAttributes<HTMLDivElement>;

/** The border lights up where the cursor is */
export function BorderGlow({
  color = '#7c5cff',
  width = 2,
  glow = 120,
  className,
  style,
  children,
  ...rest
}: BorderGlowProps) {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = trackPointer(el, writeSpotlight);
    return () => controller.revert();
  }, []);

  const vars = {
    '--jolt-color': color,
    '--jolt-width': `${width}px`,
    '--jolt-glow': `${glow}px`,
    ...style,
  } as CSSProperties;

  return (
    <div
      {...rest}
      ref={ref}
      className={`jolt-border-glow${className ? ` ${className}` : ''}`}
      style={vars}
    >
      {children}
    </div>
  );
}

// packages/svelte/src/components/BorderGlow/BorderGlow.svelte
<script lang="ts">
  import { onMount, type Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { trackPointer, writeSpotlight, type BorderGlowProps } from '@jolt/core';
  import '@jolt/core/styles/border-glow.css';

  type Props = BorderGlowProps &
    Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#7c5cff',
    width = 2,
    glow = 120,
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();

  let root: HTMLDivElement;
  onMount(() => trackPointer(root, writeSpotlight).revert);
</script>

<div
  {...rest}
  bind:this={root}
  class="jolt-border-glow {className}"
  style="--jolt-color:{color};--jolt-width:{width}px;--jolt-glow:{glow}px;{style}"
>
  {#if children}{@render children()}{/if}
</div>
