// packages/vue/src/components/ProgressBar/ProgressBar.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/progress-bar.css';

// Mirrors `progressBarSchema` in @jolt/core (see DECISIONS D-011).
interface Props {
  color?: string;
  width?: number;
  thickness?: number;
  speed?: number;
  label?: string;
}
const {
  color = '#6d5efc',
  width = 160,
  thickness = 4,
  speed = 1.4,
  label = 'Loading…',
} = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-width': `${width}px`,
  '--jolt-thickness': `${thickness}px`,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <div role="status" :aria-label="label" class="jolt-progress-bar" :style="style">
    <span />
  </div>
</template>

// packages/svelte/src/components/ProgressBar/ProgressBar.svelte
<script lang="ts">
  import type { ProgressBarProps } from '@jolt/core';
  import '@jolt/core/styles/progress-bar.css';

  let {
    color = '#6d5efc',
    width = 160,
    thickness = 4,
    speed = 1.4,
    label = 'Loading…',
  }: ProgressBarProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-progress-bar"
  style="--jolt-color:{color};--jolt-width:{width}px;--jolt-thickness:{thickness}px;--jolt-speed:{speed}s"
>
  <span></span>
</div>
