// packages/svelte/src/components/Waves/Waves.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { WavesProps } from '@jolt/core';
  import { createWaves } from '@jolt/core/webgl/waves';

  let { color, amplitude, frequency, speed, density, opacity }: WavesProps = $props();
  let root: HTMLDivElement;

  onMount(() => {
    const controller = createWaves(root, { color, amplitude, frequency, speed, density, opacity });
    return () => controller.revert();
  });
</script>

<div bind:this={root} aria-hidden="true" class="h-full w-full"></div>

// packages/react/src/components/Waves/Waves.tsx
import { useLayoutEffect, useRef } from 'react';
import type { WavesProps } from '@jolt/core';
import { createWaves } from '@jolt/core/webgl/waves';

/** A decorative undulating wireframe plane (Three.js), rendered to a full-bleed canvas. */
export function Waves({ color, amplitude, frequency, speed, density, opacity }: WavesProps) {
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = createWaves(el, { color, amplitude, frequency, speed, density, opacity });
    return () => controller.revert();
  }, [color, amplitude, frequency, speed, density, opacity]);

  return <div ref={ref} aria-hidden="true" className="h-full w-full" />;
}
