// packages/vue/src/components/Rings/Rings.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref } from 'vue';
import { createRings, type RingsController } from '@jolt/core/webgl/rings';

// Mirrors `ringsSchema` in @jolt/core (Vue's SFC compiler can't resolve the
// schema-inferred type in defineProps — see DECISIONS D-011).
interface Props {
  color?: string;
  ringCount?: number;
  pointsPerRing?: number;
  spacing?: number;
  size?: number;
  speed?: number;
  amplitude?: number;
  frequency?: number;
  opacity?: number;
}
const props = defineProps<Props>();
const root = ref<HTMLDivElement | null>(null);
let controller: RingsController | null = null;

onMounted(() => {
  if (root.value) controller = createRings(root.value, props);
});
onBeforeUnmount(() => controller?.revert());
</script>

<template>
  <div ref="root" aria-hidden="true" class="h-full w-full" />
</template>

// packages/svelte/src/components/Rings/Rings.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { RingsProps } from '@jolt/core';
  import { createRings } from '@jolt/core/webgl/rings';

  let {
    color,
    ringCount,
    pointsPerRing,
    spacing,
    size,
    speed,
    amplitude,
    frequency,
    opacity,
  }: RingsProps = $props();
  let root: HTMLDivElement;

  onMount(() => {
    const controller = createRings(root, {
      color,
      ringCount,
      pointsPerRing,
      spacing,
      size,
      speed,
      amplitude,
      frequency,
      opacity,
    });
    return () => controller.revert();
  });
</script>

<div bind:this={root} aria-hidden="true" class="h-full w-full"></div>
