// packages/vue/src/components/Ripple/Ripple.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/ripple.css';

// Mirrors `rippleSchema` in @jolt/core (see DECISIONS D-011).
interface Props {
  color?: string;
  size?: number;
  speed?: number;
  label?: string;
}
const { color = '#7c5cff', size = 48, speed = 1.2, label = 'Loading…' } = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-size': `${size}px`,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <div role="status" :aria-label="label" class="jolt-ripple" :style="style">
    <span />
    <span />
  </div>
</template>

// packages/svelte/src/components/Ripple/Ripple.svelte
<script lang="ts">
  import type { RippleProps } from '@jolt/core';
  import '@jolt/core/styles/ripple.css';

  let { color = '#7c5cff', size = 48, speed = 1.2, label = 'Loading…' }: RippleProps = $props();
</script>

<div
  role="status"
  aria-label={label}
  class="jolt-ripple"
  style="--jolt-color:{color};--jolt-size:{size}px;--jolt-speed:{speed}s"
>
  <span></span>
  <span></span>
</div>
