// packages/vue/src/components/ShinyText/ShinyText.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/shiny-text.css';

// Mirrors `shinyTextSchema` in @jolt/core (see DECISIONS D-011).
interface Props {
  text: string;
  duration?: number;
}
const { text, duration = 3 } = defineProps<Props>();

const style = computed(() => ({ '--jolt-duration': `${duration}s` }));
</script>

<template>
  <span class="jolt-shiny-text" :style="style">{{ text }}</span>
</template>

// packages/react/src/components/ShinyText/ShinyText.tsx
import type { CSSProperties } from 'react';
import type { ShinyTextProps } from '@jolt/core';
import '@jolt/core/styles/shiny-text.css';

/** CSS-only sheen sweeping across muted text (whole-text, not per-char). */
export function ShinyText({ text, duration = 3 }: ShinyTextProps) {
  const style = { '--jolt-duration': `${duration}s` } as CSSProperties;

  return (
    <span className="jolt-shiny-text" style={style}>
      {text}
    </span>
  );
}
