// packages/vue/src/components/StarBorder/StarBorder.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/star-border.css';

// Mirrors `starBorderSchema` in @jolt/core (Vue's SFC compiler can't resolve the
// schema-inferred type in defineProps — see DECISIONS D-011).
interface Props {
  color?: string;
  star?: string;
  width?: number;
  speed?: number;
  label?: string;
}
const {
  color = '#14141c',
  star = '#c6ff4f',
  width = 2,
  speed = 4,
  label = 'Button',
} = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-star': star,
  '--jolt-width': `${width}px`,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <button class="jolt-star-border" :style="style">
    <slot>{{ label }}</slot>
  </button>
</template>

// packages/svelte/src/components/StarBorder/StarBorder.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { StarBorderProps } from '@jolt/core';
  import '@jolt/core/styles/star-border.css';

  type Props = StarBorderProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#14141c',
    star = '#c6ff4f',
    width = 2,
    speed = 4,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {...rest}
  {type}
  class="jolt-star-border {className}"
  style="--jolt-color:{color};--jolt-star:{star};--jolt-width:{width}px;--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>
