// packages/vue/src/components/BorderDraw/BorderDraw.vue
<script setup lang="ts">
import { computed } from 'vue';
import '@jolt/core/styles/border-draw.css';

// Mirrors `borderDrawSchema` in @jolt/core (D-011). Native button attrs fall through
// to the single root <button>; no defineEmits.
interface Props {
  color?: string;
  speed?: number;
  label?: string;
}
const { color = '#6d5efc', speed = 3, label = 'Button' } = defineProps<Props>();

const style = computed(() => ({
  '--jolt-color': color,
  '--jolt-speed': `${speed}s`,
}));
</script>

<template>
  <button class="jolt-border-draw" :style="style">
    <slot>{{ label }}</slot>
  </button>
</template>

// packages/svelte/src/components/BorderDraw/BorderDraw.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { BorderDrawProps } from '@jolt/core';
  import '@jolt/core/styles/border-draw.css';

  type Props = BorderDrawProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#6d5efc',
    speed = 3,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {...rest}
  {type}
  class="jolt-border-draw {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>
