// packages/react/src/components/BorderDraw/BorderDraw.tsx
import type { ButtonHTMLAttributes, CSSProperties } from 'react';
import type { BorderDrawProps as BorderDrawStyleProps } from '@jolt/core';
import '@jolt/core/styles/border-draw.css';

type BorderDrawProps = BorderDrawStyleProps & ButtonHTMLAttributes<HTMLButtonElement>;

/** A ghost button with a flowing gradient border (CSS-only). Renders a real <button>. */
export function BorderDraw({
  color = '#6d5efc',
  speed = 3,
  label = 'Button',
  type = 'button',
  className,
  style,
  children,
  ...rest
}: BorderDrawProps) {
  const vars = {
    '--jolt-color': color,
    '--jolt-speed': `${speed}s`,
    ...style,
  } as CSSProperties;

  return (
    <button
      {...rest}
      type={type}
      className={`jolt-border-draw${className ? ` ${className}` : ''}`}
      style={vars}
    >
      {children ?? label}
    </button>
  );
}

// packages/svelte/src/components/BorderDraw/BorderDraw.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { BorderDrawProps } from '@jolt/core';
  import '@jolt/core/styles/border-draw.css';

  type Props = BorderDrawProps &
    Omit<HTMLButtonAttributes, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    color = '#6d5efc',
    speed = 3,
    label = 'Button',
    type = 'button',
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();
</script>

<button
  {...rest}
  {type}
  class="jolt-border-draw {className}"
  style="--jolt-color:{color};--jolt-speed:{speed}s;{style}"
  >{#if children}{@render children()}{:else}{label}{/if}</button
>
