// packages/svelte/src/components/Magnet/Magnet.svelte
<script lang="ts">
  import { onMount, type Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { trackPointer, writeMagnet, type MagnetProps } from '@jolt/core';
  import '@jolt/core/styles/magnet.css';

  type Props = MagnetProps &
    Omit<HTMLAttributes<HTMLDivElement>, 'children' | 'class' | 'style'> & {
      children?: Snippet;
      class?: string;
      style?: string;
    };

  let {
    strength = 14,
    speed = 0.25,
    class: className = '',
    style = '',
    children,
    ...rest
  }: Props = $props();

  let root: HTMLDivElement;
  // Publish a signed -1..1 pull toward the cursor; the stylesheet scales it by --jolt-strength.
  onMount(() => trackPointer(root, writeMagnet).revert);
</script>

<div
  {...rest}
  bind:this={root}
  class="jolt-magnet {className}"
  style="--jolt-strength:{strength}px;--jolt-speed:{speed}s;{style}"
>
  {#if children}{@render children()}{/if}
</div>

// packages/react/src/components/Magnet/Magnet.tsx
import { useLayoutEffect, useRef, type HTMLAttributes, type CSSProperties } from 'react';
import { trackPointer, writeMagnet, type MagnetProps as MagnetStyleProps } from '@jolt/core';
import '@jolt/core/styles/magnet.css';

type MagnetProps = MagnetStyleProps & HTMLAttributes<HTMLDivElement>;

/** Pulls your content toward the cursor */
export function Magnet({
  strength = 14,
  speed = 0.25,
  className,
  style,
  children,
  ...rest
}: MagnetProps) {
  const ref = useRef<HTMLDivElement>(null);

  // Publish a signed -1..1 pull toward the cursor; the stylesheet scales it by --jolt-strength.
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const controller = trackPointer(el, writeMagnet);
    return () => controller.revert();
  }, []);

  const vars = {
    '--jolt-strength': `${strength}px`,
    '--jolt-speed': `${speed}s`,
    ...style,
  } as CSSProperties;

  return (
    <div
      {...rest}
      ref={ref}
      className={`jolt-magnet${className ? ` ${className}` : ''}`}
      style={vars}
    >
      {children}
    </div>
  );
}
